### ISSUE TITLE
Cannot find module 'shelljs/global 

### ISSUE THREAD

**Issue by krongk** [xiaohui-zhangxh/vue-webpack-cordova#2]
when run 
`vue init xiaohui-zhangxh/vue-webpack-cordova my-project `

the error shows:

`Error: Cannot find module 'shelljs'`

**Comment by krongk** [comment]
resolved it follow:  https://github.com/creationix/nvm/issues/586

add below to  ~/.bashrc :

export NODE_PATH=$NODE_PATH:`npm root -g`

**Comment by xiaohui-zhangxh** [comment]
This error is not about `vue-webpack-cordova`, it's about Node Version Manager `nvm`, you didn't set it up properly.
